# Generated by Django 3.1.3 on 2020-11-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Content')),
                ('published', models.DateTimeField(verbose_name='Publish Date')),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
    ]
